/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emuladorprocesadorz80;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class pastillaZ80 extends javax.swing.JDialog {

    /**
     * Creates new form pastillaZ80
     */
    
    public static EmuladorProcesadorZ80 procesador = new EmuladorProcesadorZ80();
    
    public static char []  A = "0000000000000000".toCharArray();
    
    public pastillaZ80() {
        initComponents();
        pastilla.setBorder(BorderFactory.createLineBorder(Color.black));
        pastilla.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pastilla = new javax.swing.JLabel();
        A0 = new javax.swing.JRadioButton();
        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        A4 = new javax.swing.JRadioButton();
        A5 = new javax.swing.JRadioButton();
        A6 = new javax.swing.JRadioButton();
        A7 = new javax.swing.JRadioButton();
        A8 = new javax.swing.JRadioButton();
        A9 = new javax.swing.JRadioButton();
        A10 = new javax.swing.JRadioButton();
        A11 = new javax.swing.JRadioButton();
        A12 = new javax.swing.JRadioButton();
        A13 = new javax.swing.JRadioButton();
        A14 = new javax.swing.JRadioButton();
        A15 = new javax.swing.JRadioButton();
        D0 = new javax.swing.JRadioButton();
        D1 = new javax.swing.JRadioButton();
        D2 = new javax.swing.JRadioButton();
        D3 = new javax.swing.JRadioButton();
        D4 = new javax.swing.JRadioButton();
        D5 = new javax.swing.JRadioButton();
        D6 = new javax.swing.JRadioButton();
        D7 = new javax.swing.JRadioButton();
        M1 = new javax.swing.JRadioButton();
        MREQ = new javax.swing.JRadioButton();
        IORQ = new javax.swing.JRadioButton();
        RD = new javax.swing.JRadioButton();
        WR = new javax.swing.JRadioButton();
        RFSH = new javax.swing.JRadioButton();
        HALT = new javax.swing.JRadioButton();
        WAIT = new javax.swing.JRadioButton();
        INT = new javax.swing.JRadioButton();
        NMI = new javax.swing.JRadioButton();
        RESET = new javax.swing.JRadioButton();
        BUSRQ = new javax.swing.JRadioButton();
        BUSACK = new javax.swing.JRadioButton();
        CLK = new javax.swing.JRadioButton();
        V = new javax.swing.JRadioButton();
        GND = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 650));

        pastilla.setText("Z80 CPU");

        A0.setText("A0");

        A1.setText("A1");

        A2.setText("A2");

        A3.setText("A3");

        A4.setText("A4");

        A5.setText("A5");

        A6.setText("A6");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });

        A7.setText("A7");

        A8.setText("A8");
        A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A8ActionPerformed(evt);
            }
        });

        A9.setText("A9");

        A10.setText("A10");

        A11.setText("A11");

        A12.setText("A12");

        A13.setText("A13");

        A14.setText("A14");
        A14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A14ActionPerformed(evt);
            }
        });

        A15.setText("A15");

        D0.setText("D0");

        D1.setText("D1");

        D2.setText("D2");

        D3.setText("D3");

        D4.setText("D4");

        D5.setText("D5");

        D6.setText("D6");

        D7.setText("D7");

        M1.setText("M1");

        MREQ.setText("MREQ");

        IORQ.setText("IORQ");

        RD.setText("RD");

        WR.setText("WR");

        RFSH.setText("RFSH");
        RFSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFSHActionPerformed(evt);
            }
        });

        HALT.setText("HALT");
        HALT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HALTActionPerformed(evt);
            }
        });

        WAIT.setText("WAIT");
        WAIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAITActionPerformed(evt);
            }
        });

        INT.setText("INT");

        NMI.setText("NMI");

        RESET.setText("RESET");

        BUSRQ.setText("BUSRQ");
        BUSRQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSRQActionPerformed(evt);
            }
        });

        BUSACK.setText("BUSACK");

        CLK.setText("CLK");

        V.setText("+5V");

        GND.setText("GND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(M1)
                    .addComponent(MREQ)
                    .addComponent(IORQ)
                    .addComponent(RD)
                    .addComponent(WR)
                    .addComponent(RFSH)
                    .addComponent(HALT)
                    .addComponent(WAIT)
                    .addComponent(INT)
                    .addComponent(NMI)
                    .addComponent(RESET)
                    .addComponent(BUSRQ)
                    .addComponent(BUSACK)
                    .addComponent(CLK)
                    .addComponent(V)
                    .addComponent(GND))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pastilla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A0)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4)
                    .addComponent(A5)
                    .addComponent(A6)
                    .addComponent(A7)
                    .addComponent(A8)
                    .addComponent(A9)
                    .addComponent(A10)
                    .addComponent(A11)
                    .addComponent(A12)
                    .addComponent(A13)
                    .addComponent(A14)
                    .addComponent(A15)
                    .addComponent(D0)
                    .addComponent(D1)
                    .addComponent(D2)
                    .addComponent(D3)
                    .addComponent(D4)
                    .addComponent(D5)
                    .addComponent(D6)
                    .addComponent(D7))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A15)
                        .addGap(27, 27, 27)
                        .addComponent(D0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D7))
                    .addComponent(pastilla, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(M1)
                        .addGap(18, 18, 18)
                        .addComponent(MREQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IORQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RFSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HALT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WAIT)
                        .addGap(18, 18, 18)
                        .addComponent(INT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NMI)
                        .addGap(22, 22, 22)
                        .addComponent(RESET)
                        .addGap(18, 18, 18)
                        .addComponent(BUSRQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSACK)
                        .addGap(82, 82, 82)
                        .addComponent(CLK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GND)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6ActionPerformed

    private void A8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A8ActionPerformed

    private void A14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A14ActionPerformed

    private void BUSRQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSRQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUSRQActionPerformed

    private void RFSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RFSHActionPerformed

    private void HALTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HALTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HALTActionPerformed

    private void WAITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAITActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A0;
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A10;
    private javax.swing.JRadioButton A11;
    private javax.swing.JRadioButton A12;
    private javax.swing.JRadioButton A13;
    private javax.swing.JRadioButton A14;
    private javax.swing.JRadioButton A15;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton A4;
    private javax.swing.JRadioButton A5;
    private javax.swing.JRadioButton A6;
    private javax.swing.JRadioButton A7;
    private javax.swing.JRadioButton A8;
    private javax.swing.JRadioButton A9;
    private javax.swing.JRadioButton BUSACK;
    private javax.swing.JRadioButton BUSRQ;
    private javax.swing.JRadioButton CLK;
    private javax.swing.JRadioButton D0;
    private javax.swing.JRadioButton D1;
    private javax.swing.JRadioButton D2;
    private javax.swing.JRadioButton D3;
    private javax.swing.JRadioButton D4;
    private javax.swing.JRadioButton D5;
    private javax.swing.JRadioButton D6;
    private javax.swing.JRadioButton D7;
    private javax.swing.JRadioButton GND;
    private javax.swing.JRadioButton HALT;
    private javax.swing.JRadioButton INT;
    private javax.swing.JRadioButton IORQ;
    private javax.swing.JRadioButton M1;
    private javax.swing.JRadioButton MREQ;
    private javax.swing.JRadioButton NMI;
    private javax.swing.JRadioButton RD;
    private javax.swing.JRadioButton RESET;
    private javax.swing.JRadioButton RFSH;
    private javax.swing.JRadioButton V;
    private javax.swing.JRadioButton WAIT;
    private javax.swing.JRadioButton WR;
    private javax.swing.JLabel pastilla;
    // End of variables declaration//GEN-END:variables

    public void setteardireciones(){
        
        A = procesador.getDirecciones();
        
        if (A[0]=='1') {
            A0.setSelected(true);
            System.out.println("A0 sirve");
        }else{
            A0.setSelected(false);
        }
        
        if (A[1]=='1') {
            A1.setSelected(true);
            System.out.println("A1 sirve");
        }else{
            A1.setSelected(false);
        }
        
        if (A[2]=='1') {
            A2.setSelected(true);
            System.out.println("A2 sirve");
        }else{
            A2.setSelected(false);
        }
        
        if (A[3]=='1') {
            A3.setSelected(true);
            System.out.println("A3 sirve");
        }else{
            A3.setSelected(false);
        }
        
        if (A[4]=='1') {
            A4.setSelected(true);
        }else{
            A4.setSelected(false);
        }
        
        if (A[5]=='1') {
            A5.setSelected(true);
        }else{
            A5.setSelected(false);
        }
        
        if (A[6]=='1') {
            A6.setSelected(true);
        }else{
            A6.setSelected(false);
        }
        
        if (A[7]=='1') {
            A7.setSelected(true);
        }else{
            A7.setSelected(false);
        }
        
        if (A[8]=='1') {
            A8.setSelected(true);
        }else{
            A8.setSelected(false);
        }
        
        if (A[9]=='1') {
            A9.setSelected(true);
        }else{
            A9.setSelected(false);
        }
        
        if (A[10]=='1') {
            A10.setSelected(true);
        }else{
            A10.setSelected(false);
        }
        
        if (A[11]=='1') {
            A11.setSelected(true);
        }else{
            A11.setSelected(false);
        }
        
        if (A[12]=='1') {
            A12.setSelected(true);
        }else{
            A12.setSelected(false);
        }
        
        if (A[13]=='1') {
            A13.setSelected(true);
        }else{
            A13.setSelected(false);
        }
        
        if (A[14]=='1') {
            A14.setSelected(true);
        }else{
            A14.setSelected(false);
        }
        
        if (A[15]=='1') {
            A15.setSelected(true);
        }else{
            A15.setSelected(false);
        }
        
        
    }

}
