
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package emuladorprocesadorz80;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVEDE = 33;
  public static final int DOSPUNTOS = 35;
  public static final int CASO = 40;
  public static final int Y = 6;
  public static final int ASIGNAR = 29;
  public static final int MULT = 15;
  public static final int OTRO = 45;
  public static final int SI = 36;
  public static final int LLAVEIZ = 32;
  public static final int DIFERENTE = 8;
  public static final int O = 5;
  public static final int MATRIZ = 26;
  public static final int ENTONCES = 4;
  public static final int INT = 22;
  public static final int PAREN_CI = 31;
  public static final int IGUAL = 7;
  public static final int MIENTRAS = 38;
  public static final int BOOL = 25;
  public static final int TERMINA = 3;
  public static final int DIV = 16;
  public static final int SUMA = 13;
  public static final int SELECCIONAR = 39;
  public static final int ALGORITMO = 2;
  public static final int MAY_IGUAL = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int MENOS = 14;
  public static final int MENOR = 10;
  public static final int MOD = 17;
  public static final int VECTOR = 27;
  public static final int PCOMA = 28;
  public static final int MAYOR = 9;
  public static final int ROMPER = 41;
  public static final int POTENCIA = 18;
  public static final int NO = 19;
  public static final int MEN_IGUAL = 12;
  public static final int FLOAT = 23;
  public static final int PAREN_AP = 30;
  public static final int HACER = 42;
  public static final int STRING = 24;
  public static final int PARA = 43;
  public static final int DEF = 20;
  public static final int RETORNAR = 21;
  public static final int DEFECTO = 44;
  public static final int SI_NO = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALGORITMO",
  "TERMINA",
  "ENTONCES",
  "O",
  "Y",
  "IGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAY_IGUAL",
  "MEN_IGUAL",
  "SUMA",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "POTENCIA",
  "NO",
  "DEF",
  "RETORNAR",
  "INT",
  "FLOAT",
  "STRING",
  "BOOL",
  "MATRIZ",
  "VECTOR",
  "PCOMA",
  "ASIGNAR",
  "PAREN_AP",
  "PAREN_CI",
  "LLAVEIZ",
  "LLAVEDE",
  "COMA",
  "DOSPUNTOS",
  "SI",
  "SI_NO",
  "MIENTRAS",
  "SELECCIONAR",
  "CASO",
  "ROMPER",
  "HACER",
  "PARA",
  "DEFECTO",
  "OTRO"
  };
}

